### ISSUE TITLE
Larger image than thumbnail?

### ISSUE THREAD

**Issue by kylankob** [scottdixon/react-native-upload-from-camera-roll#1]
@scottdixon Instead of this uploading the thumbnail size of the image, can it be modified to upload a larger version? Thanks.

**Comment by scottdixon** [comment]
Sure, @kylankob.

Check out line 26 of RCTCustom.m. You can update the Objective C to pull the full resolution image instead of the thumbnail.

Let me know if you need a hand.

**Comment by guillaumepiot** [comment]
Hi @scottdixon, thank you for the great example.

I'm new to Objective-C and I'm struggling to modify line 26 to get the full res image, do you have an example for it?

**Comment by guillaumepiot** [comment]
I have figure it out in case someone is encountering the same issue. I have replaced line 26 with:

```
ALAssetRepresentation *representation = [asset defaultRepresentation];
CGImageRef imageRef = [representation fullResolutionImage];
```

Also I have increase the compression of the JPG image to 0.7:

```
NSData *imageData = UIImageJPEGRepresentation([UIImage imageWithCGImage:imageRef], 0.7);
```

**Comment by brendanscarano** [comment]
Hey @scottdixon - thank you for this awesome solution, I've found it extremely helpful!

I'm not too familiar with Objective-C and I was wondering if there was a way I could convert the image to be a higher resolution than a thumbnail, but slightly less than what @guillaumepiot has done above. Would I use his solution to achieve this but decrease the compression of the JPG image or should I not be converting it to fullResolutionImage?

**Comment by scottdixon** [comment]
Hey @brendanscarano - it comes built-in now, no need to mess with Objective-C :)
https://stackoverflow.com/questions/29489502/how-to-upload-file-to-server-using-react-native/36124650#36124650
