### ISSUE TITLE
Request for upload for image taken directly from camera

### ISSUE THREAD

**Issue by shahchirag** [scottdixon/react-native-upload-from-camera-roll#2]
@scottdixon : Its more of a request as I don't know much about objective C. Thought you might help or provide guidance. 

I see from the code that you create an ALAssetsLibrary instance which provides access to the videos and photos that are under the control of the Photos application. What I want is to access images taken from the camera within the application which are not stored on the camera roll yet. 

What I also see is you open the image from the camera roll, perform some operations and return base64 encoded string. Would it be possible to do that for the images of the camera? Can you create a separate .m file just for camera. Thanks.

**Comment by scottdixon** [comment]
Hi There,

For base64 data of the camera, try this plugin: https://github.com/lwansbrough/react-native-camera

Good luck.
